import { NextRequest, NextResponse } from "next/server";

import { getListingsByBbox } from "@/src/lib/db/queries";
import { ShortTermRentalListing } from "@/src/types/listings";

export const dynamic = "force-static";

const FALLBACK_LISTINGS: ShortTermRentalListing[] = [
  // Italy
  {
    id: "fb-it-1",
    title: "Loft panoramico nel centro di Roma",
    description: "Splendido loft con vista sulla città, a pochi passi dal Colosseo. Arredato con gusto, dotato di ogni comfort.",
    nightlyPrice: 130,
    currency: "EUR",
    platform: "CityOpenData",
    rating: 4.7,
    reviewCount: 128,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Loft",
    latitude: 41.8902,
    longitude: 12.4922,
    address: "Rione Monti",
    city: "Rome",
    countryCode: "IT",
    originalUrl: "https://www.airbnb.com/rooms/12345678",
    sourceListingId: "fb-it-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-it-2",
    title: "Appartamento storico a Trastevere",
    description: "Charming apartment in the heart of Trastevere, 5-minute walk from Santa Maria church. Exposed brick walls, modern kitchen.",
    nightlyPrice: 95,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 312,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 41.8877,
    longitude: 12.4697,
    address: "Trastevere",
    city: "Rome",
    countryCode: "IT",
    originalUrl: "https://www.airbnb.com/rooms/23456789",
    sourceListingId: "fb-it-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-it-3",
    title: "Studio con terrazza a Firenze",
    description: "Luminoso studio con terrazza privata in Oltrarno, vista sui tetti di Firenze. A 10 minuti a piedi da Palazzo Pitti.",
    nightlyPrice: 110,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 87,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Studio",
    latitude: 43.7649,
    longitude: 11.2439,
    address: "Oltrarno",
    city: "Florence",
    countryCode: "IT",
    originalUrl: "https://www.airbnb.com/rooms/34567890",
    sourceListingId: "fb-it-3",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-it-4",
    title: "Appartamento con vista sul Canal Grande – Venezia",
    description: "Straordinario bilocale affacciato direttamente sul Canal Grande. Travi originali a vista, parquet antico, bagno in marmo.",
    nightlyPrice: 280,
    currency: "EUR",
    platform: "Booking",
    rating: 4.9,
    reviewCount: 194,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 45.4382,
    longitude: 12.3259,
    address: "San Polo",
    city: "Venice",
    countryCode: "IT",
    originalUrl: "https://www.booking.com/hotel/it/canal-grande-suite.html",
    sourceListingId: "fb-it-4",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-it-5",
    title: "Villa con piscina sulle colline del Chianti",
    description: "Bellissima villa toscana del 1700 ristrutturata, con piscina panoramica, uliveto e vigneto privati. Ideale per gruppi.",
    nightlyPrice: 650,
    currency: "EUR",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 56,
    maxGuests: 10,
    bedrooms: 5,
    bathrooms: 4,
    propertyType: "Villa",
    latitude: 43.471,
    longitude: 11.3236,
    address: "Greve in Chianti",
    city: "Greve in Chianti",
    countryCode: "IT",
    originalUrl: "https://www.vrbo.com/1234567",
    sourceListingId: "fb-it-5",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-it-6",
    title: "Mansarda nel centro di Milano",
    description: "Accogliente mansarda con terrazzo nel cuore di Brera. Modernamente arredata, vicino a Pinacoteca di Brera e Corso Como.",
    nightlyPrice: 145,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.7,
    reviewCount: 221,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Loft",
    latitude: 45.4764,
    longitude: 9.1885,
    address: "Brera",
    city: "Milan",
    countryCode: "IT",
    originalUrl: "https://www.airbnb.com/rooms/45678901",
    sourceListingId: "fb-it-6",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Spain
  {
    id: "fb-es-1",
    title: "Appartamento vista mare a Barceloneta",
    description: "Bilocale luminoso a 2 minuti a piedi dalla spiaggia di Barceloneta. Balcone con vista mare, aria condizionata.",
    nightlyPrice: 160,
    currency: "EUR",
    platform: "AnalyticsProvider",
    rating: 4.8,
    reviewCount: 204,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 41.3789,
    longitude: 2.1904,
    address: "Barceloneta",
    city: "Barcelona",
    countryCode: "ES",
    originalUrl: "https://www.airbnb.com/rooms/56789012",
    sourceListingId: "fb-es-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-es-2",
    title: "Penthouse nel Barrio Gótico – Barcellona",
    description: "Fantastico attico con terrazza panoramica nel cuore del quartiere gotico di Barcellona. Design contemporaneo.",
    nightlyPrice: 320,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 143,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Penthouse",
    latitude: 41.383,
    longitude: 2.1776,
    address: "Barrio Gótico",
    city: "Barcelona",
    countryCode: "ES",
    originalUrl: "https://www.airbnb.com/rooms/67890123",
    sourceListingId: "fb-es-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-es-3",
    title: "Studio moderno a Madrid – Centro",
    description: "Studio completamente ristrutturato a Malasaña, il quartiere hipster di Madrid. Vicino a Chueca e Gran Vía.",
    nightlyPrice: 85,
    currency: "EUR",
    platform: "Booking",
    rating: 4.6,
    reviewCount: 98,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Studio",
    latitude: 40.4266,
    longitude: -3.7038,
    address: "Malasaña",
    city: "Madrid",
    countryCode: "ES",
    originalUrl: "https://www.booking.com/hotel/es/malasana-studio.html",
    sourceListingId: "fb-es-3",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-es-4",
    title: "Villa con piscina a Ibiza – Playa d'en Bossa",
    description: "Lussuosa villa a 5 minuti dalla spiaggia di Playa d'en Bossa. Piscina privata, terrazza panoramica, BBQ.",
    nightlyPrice: 890,
    currency: "EUR",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 38,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Villa",
    latitude: 38.8784,
    longitude: 1.4082,
    address: "Playa d'en Bossa",
    city: "Ibiza",
    countryCode: "ES",
    originalUrl: "https://www.vrbo.com/2345678",
    sourceListingId: "fb-es-4",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // France
  {
    id: "fb-fr-1",
    title: "Appartement Haussmannien nel Marais – Parigi",
    description: "Splendido appartamento in stile haussmanniano nel cuore del Marais. Soffitti alti, parquet originale, camino.",
    nightlyPrice: 210,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 376,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 48.8567,
    longitude: 2.3522,
    address: "Le Marais",
    city: "Paris",
    countryCode: "FR",
    originalUrl: "https://www.airbnb.com/rooms/78901234",
    sourceListingId: "fb-fr-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-fr-2",
    title: "Studio con vista Torre Eiffel – Parigi",
    description: "Delizioso studio al 6° piano con balcone e vista diretta sulla Torre Eiffel. Posizione ideale nel 7° arrondissement.",
    nightlyPrice: 185,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 521,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Studio",
    latitude: 48.8584,
    longitude: 2.2945,
    address: "7ème arrondissement",
    city: "Paris",
    countryCode: "FR",
    originalUrl: "https://www.airbnb.com/rooms/89012345",
    sourceListingId: "fb-fr-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-fr-3",
    title: "Mas provenzale con lavanda – Gordes",
    description: "Autentico mas provenzale immerso nei campi di lavanda vicino a Gordes, uno dei borghi più belli di Francia.",
    nightlyPrice: 420,
    currency: "EUR",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 72,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "House",
    latitude: 43.9128,
    longitude: 5.1963,
    address: "Gordes",
    city: "Gordes",
    countryCode: "FR",
    originalUrl: "https://www.vrbo.com/3456789",
    sourceListingId: "fb-fr-3",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // United Kingdom
  {
    id: "fb-gb-1",
    title: "Victorian Townhouse a Notting Hill – Londra",
    description: "Elegante townhouse vittoriana su 4 piani in Notting Hill. Garden patio privato, cucina moderna, 5 minuti dalla metropolitana.",
    nightlyPrice: 340,
    currency: "GBP",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 167,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "House",
    latitude: 51.5159,
    longitude: -0.1963,
    address: "Notting Hill",
    city: "London",
    countryCode: "GB",
    originalUrl: "https://www.airbnb.com/rooms/90123456",
    sourceListingId: "fb-gb-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-gb-2",
    title: "Modern Studio a Shoreditch – Londra",
    description: "Trendy studio design a Shoreditch, il quartiere creativo di Londra. Vicino a Brick Lane, Old Street e Spitalfields Market.",
    nightlyPrice: 125,
    currency: "GBP",
    platform: "Booking",
    rating: 4.6,
    reviewCount: 289,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Studio",
    latitude: 51.5225,
    longitude: -0.077,
    address: "Shoreditch",
    city: "London",
    countryCode: "GB",
    originalUrl: "https://www.booking.com/hotel/gb/shoreditch-studio.html",
    sourceListingId: "fb-gb-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Netherlands
  {
    id: "fb-nl-1",
    title: "Canal House ad Amsterdam – Jordaan",
    description: "Incantevole canal house del XVII secolo nel quartiere Jordaan. Travi originali, vista sui canali, vicino ai musei.",
    nightlyPrice: 195,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 445,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "House",
    latitude: 52.3737,
    longitude: 4.8842,
    address: "Jordaan",
    city: "Amsterdam",
    countryCode: "NL",
    originalUrl: "https://www.airbnb.com/rooms/11223344",
    sourceListingId: "fb-nl-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Germany
  {
    id: "fb-de-1",
    title: "Altbau-Wohnung a Prenzlauer Berg – Berlino",
    description: "Spaziosa Altbau (stile antico) nel vivace quartiere Prenzlauer Berg. Soffitti a stucco, parquet, cucina attrezzata.",
    nightlyPrice: 98,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.7,
    reviewCount: 183,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 52.5387,
    longitude: 13.4156,
    address: "Prenzlauer Berg",
    city: "Berlin",
    countryCode: "DE",
    originalUrl: "https://www.airbnb.com/rooms/22334455",
    sourceListingId: "fb-de-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-de-2",
    title: "Design Loft a Monaco di Baviera – Maxvorstadt",
    description: "Moderno loft in un edificio storico ristrutturato a Maxvorstadt, vicino all'English Garden e ai grandi musei.",
    nightlyPrice: 135,
    currency: "EUR",
    platform: "Booking",
    rating: 4.8,
    reviewCount: 97,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Loft",
    latitude: 48.155,
    longitude: 11.5679,
    address: "Maxvorstadt",
    city: "Munich",
    countryCode: "DE",
    originalUrl: "https://www.booking.com/hotel/de/maxvorstadt-loft.html",
    sourceListingId: "fb-de-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Portugal
  {
    id: "fb-pt-1",
    title: "Appartamento con vista castello ad Alfama – Lisbona",
    description: "Tipico appartamento portoghese ad Alfama con vista sul Castello di São Jorge. Azulejos originali, grande terrazzo.",
    nightlyPrice: 120,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 338,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 38.7143,
    longitude: -9.1324,
    address: "Alfama",
    city: "Lisbon",
    countryCode: "PT",
    originalUrl: "https://www.airbnb.com/rooms/33445566",
    sourceListingId: "fb-pt-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-pt-2",
    title: "Casa bohémien nel quartiere Bonfim – Porto",
    description: "Charmante casa restaurata nel Bonfim con azulejos originali, patio privato, vicino ai migliori ristoranti di Porto.",
    nightlyPrice: 105,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 211,
    maxGuests: 5,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "House",
    latitude: 41.1468,
    longitude: -8.5953,
    address: "Bonfim",
    city: "Porto",
    countryCode: "PT",
    originalUrl: "https://www.airbnb.com/rooms/44556677",
    sourceListingId: "fb-pt-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Austria
  {
    id: "fb-at-1",
    title: "Altstadt-Appartement vicino all'Opera – Vienna",
    description: "Elegante appartamento d'epoca nel primo distretto di Vienna, a 5 minuti a piedi dall'Opera di Stato e dalla Ringstraße.",
    nightlyPrice: 175,
    currency: "EUR",
    platform: "Booking",
    rating: 4.8,
    reviewCount: 254,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 48.2032,
    longitude: 16.3695,
    address: "1. Bezirk (Innere Stadt)",
    city: "Vienna",
    countryCode: "AT",
    originalUrl: "https://www.booking.com/hotel/at/vienna-opera-apartment.html",
    sourceListingId: "fb-at-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Czech Republic
  {
    id: "fb-cz-1",
    title: "Appartamento nel Quartiere Ebraico – Praga",
    description: "Raffinato appartamento nel Josefov (quartiere ebraico), a pochi passi dal Ponte Carlo e dal Museo Nazionale.",
    nightlyPrice: 115,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.7,
    reviewCount: 189,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 50.0904,
    longitude: 14.4157,
    address: "Josefov",
    city: "Prague",
    countryCode: "CZ",
    originalUrl: "https://www.airbnb.com/rooms/55667788",
    sourceListingId: "fb-cz-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Hungary
  {
    id: "fb-hu-1",
    title: "Ruin Bar District Apartment – Budapest",
    description: "Trendy apartment nel famoso quartiere dei ruin bar di Budapest, vicino al Szimpla Kert e alle terme Széchenyi.",
    nightlyPrice: 90,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 302,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 47.4985,
    longitude: 19.0672,
    address: "VII. kerület (Erzsébetváros)",
    city: "Budapest",
    countryCode: "HU",
    originalUrl: "https://www.airbnb.com/rooms/66778899",
    sourceListingId: "fb-hu-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Croatia
  {
    id: "fb-hr-1",
    title: "Appartamento dentro le Mura di Dubrovnik",
    description: "Raro appartamento all'interno delle mura medievali di Dubrovnik con vista sul mare Adriatico. Autenticamente restaurato.",
    nightlyPrice: 320,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 127,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 42.6403,
    longitude: 18.1083,
    address: "Grad (Stari Grad)",
    city: "Dubrovnik",
    countryCode: "HR",
    originalUrl: "https://www.airbnb.com/rooms/77889900",
    sourceListingId: "fb-hr-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Greece
  {
    id: "fb-gr-1",
    title: "Suite con piscina a sfioro a Santorini – Oia",
    description: "Suite di lusso con piscina privata a sfioro e vista panoramica sulla caldera di Santorini. Tramonto indimenticabile.",
    nightlyPrice: 780,
    currency: "EUR",
    platform: "Booking",
    rating: 4.9,
    reviewCount: 89,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Suite",
    latitude: 36.4618,
    longitude: 25.3752,
    address: "Oia",
    city: "Santorini",
    countryCode: "GR",
    originalUrl: "https://www.booking.com/hotel/gr/oia-infinity-suite.html",
    sourceListingId: "fb-gr-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-gr-2",
    title: "Casa tradizionale nel Plaka – Atene",
    description: "Autentica casa neoclassica nel quartiere Plaka, ai piedi dell'Acropoli. Terrazza con vista sull'Eretteo.",
    nightlyPrice: 145,
    currency: "EUR",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 198,
    maxGuests: 5,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "House",
    latitude: 37.9745,
    longitude: 23.7285,
    address: "Plaka",
    city: "Athens",
    countryCode: "GR",
    originalUrl: "https://www.airbnb.com/rooms/88990011",
    sourceListingId: "fb-gr-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // United States
  {
    id: "fb-us-1",
    title: "Modern Loft in Brooklyn – Williamsburg",
    description: "Spacious industrial loft in the heart of Williamsburg, Brooklyn. Exposed brick, high ceilings, rooftop access with Manhattan views.",
    nightlyPrice: 175,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 412,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Loft",
    latitude: 40.7136,
    longitude: -73.9658,
    address: "Williamsburg, Brooklyn",
    city: "New York",
    countryCode: "US",
    originalUrl: "https://www.airbnb.com/rooms/99001122",
    sourceListingId: "fb-us-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-us-2",
    title: "Luxury Condo in South Beach – Miami",
    description: "Stunning ocean-view condo on the 18th floor in South Beach. Pool, gym, concierge service. Steps from the beach.",
    nightlyPrice: 390,
    currency: "USD",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 76,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "Condo",
    latitude: 25.7753,
    longitude: -80.1304,
    address: "South Beach",
    city: "Miami",
    countryCode: "US",
    originalUrl: "https://www.vrbo.com/4567890",
    sourceListingId: "fb-us-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-us-3",
    title: "Craftsman Bungalow in Silver Lake – Los Angeles",
    description: "Charming craftsman bungalow with private garden in trendy Silver Lake. Walkable to cafes, restaurants, and the Silver Lake Reservoir.",
    nightlyPrice: 220,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 154,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "House",
    latitude: 34.0872,
    longitude: -118.2707,
    address: "Silver Lake",
    city: "Los Angeles",
    countryCode: "US",
    originalUrl: "https://www.airbnb.com/rooms/10111213",
    sourceListingId: "fb-us-3",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-us-4",
    title: "Victorian Home in Pacific Heights – San Francisco",
    description: "Beautifully restored Victorian home with garden and Bay views in Pacific Heights. Walk to Union Street boutiques and restaurants.",
    nightlyPrice: 310,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.7,
    reviewCount: 203,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "House",
    latitude: 37.7929,
    longitude: -122.4359,
    address: "Pacific Heights",
    city: "San Francisco",
    countryCode: "US",
    originalUrl: "https://www.airbnb.com/rooms/11223355",
    sourceListingId: "fb-us-4",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Japan
  {
    id: "fb-jp-1",
    title: "Machiya tradizionale a Gion – Kyoto",
    description: "Autentica machiya (casa di città giapponese) del XVIII secolo a Gion, perfettamente restaurata. Giardino zen privato.",
    nightlyPrice: 50000,
    currency: "JPY",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 234,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "House",
    latitude: 35.0035,
    longitude: 135.7749,
    address: "Gion",
    city: "Kyoto",
    countryCode: "JP",
    originalUrl: "https://www.airbnb.com/rooms/22334466",
    sourceListingId: "fb-jp-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-jp-2",
    title: "Appartamento a Shinjuku – Tokyo",
    description: "Appartamento moderno in posizione centrale a Shinjuku, a 5 minuti dalla stazione. Vista panoramica sul Monte Fuji nelle giornate limpide.",
    nightlyPrice: 120,
    currency: "USD",
    platform: "Booking",
    rating: 4.7,
    reviewCount: 389,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Apartment",
    latitude: 35.6938,
    longitude: 139.7034,
    address: "Shinjuku",
    city: "Tokyo",
    countryCode: "JP",
    originalUrl: "https://www.booking.com/hotel/jp/shinjuku-apartment.html",
    sourceListingId: "fb-jp-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Australia
  {
    id: "fb-au-1",
    title: "Beachfront House a Bondi Beach – Sydney",
    description: "Incredibile casa a 50 metri dalla famosa Bondi Beach. Terrazza sul tetto, parcheggio, BBQ. Ideale per famiglie.",
    nightlyPrice: 520,
    currency: "AUD",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 142,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "House",
    latitude: -33.8914,
    longitude: 151.2767,
    address: "Bondi Beach",
    city: "Sydney",
    countryCode: "AU",
    originalUrl: "https://www.airbnb.com/rooms/33445577",
    sourceListingId: "fb-au-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "fb-au-2",
    title: "Appartamento con vista Port Jackson – Sydney CBD",
    description: "Lussuoso appartamento al 22° piano con viste spettacolari sul Porto di Sydney e sull'Opera House. Concierge 24h.",
    nightlyPrice: 295,
    currency: "AUD",
    platform: "Booking",
    rating: 4.8,
    reviewCount: 211,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "Apartment",
    latitude: -33.8668,
    longitude: 151.2093,
    address: "Sydney CBD",
    city: "Sydney",
    countryCode: "AU",
    originalUrl: "https://www.booking.com/hotel/au/sydney-harbour-view.html",
    sourceListingId: "fb-au-2",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // United Arab Emirates
  {
    id: "fb-ae-1",
    title: "Penthouse con vista Burj Khalifa – Dubai Downtown",
    description: "Esclusivo penthouse con piscina privata e terrazza panoramica con vista diretta sul Burj Khalifa e sul Dubai Fountain.",
    nightlyPrice: 1250,
    currency: "USD",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 43,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "Penthouse",
    latitude: 25.1972,
    longitude: 55.2744,
    address: "Downtown Dubai",
    city: "Dubai",
    countryCode: "AE",
    originalUrl: "https://www.vrbo.com/5678901",
    sourceListingId: "fb-ae-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Thailand
  {
    id: "fb-th-1",
    title: "Condo vista fiume a Silom – Bangkok",
    description: "Moderno condo con vista sul fiume Chao Phraya nel cuore di Silom. Piscina condominiale, palestra, vicino alla metropolitana.",
    nightlyPrice: 85,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.7,
    reviewCount: 142,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Condo",
    latitude: 13.7248,
    longitude: 100.5227,
    address: "Silom",
    city: "Bangkok",
    countryCode: "TH",
    originalUrl: "https://www.airbnb.com/rooms/44556688",
    sourceListingId: "fb-th-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Indonesia (Bali)
  {
    id: "fb-id-1",
    title: "Villa con piscina a sfioro a Ubud – Bali",
    description: "Incantevole villa balinese con piscina a sfioro panoramica sulle risaie di Ubud. Colazione inclusa, yoga al mattino.",
    nightlyPrice: 195,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 287,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "Villa",
    latitude: -8.5069,
    longitude: 115.2625,
    address: "Ubud",
    city: "Ubud",
    countryCode: "ID",
    originalUrl: "https://www.airbnb.com/rooms/55667799",
    sourceListingId: "fb-id-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Mexico
  {
    id: "fb-mx-1",
    title: "Casa coloniale a Coyoacán – Città del Messico",
    description: "Bellissima casa coloniale del '900 a Coyoacán, lo stesso quartiere di Frida Kahlo. Patio fiorito, libreria, cucina messicana.",
    nightlyPrice: 95,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 176,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "House",
    latitude: 19.3432,
    longitude: -99.1617,
    address: "Coyoacán",
    city: "Mexico City",
    countryCode: "MX",
    originalUrl: "https://www.airbnb.com/rooms/66778811",
    sourceListingId: "fb-mx-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Brazil
  {
    id: "fb-br-1",
    title: "Cobertura vista Praia de Ipanema – Rio de Janeiro",
    description: "Lussuosa cobertura duplex con terrazza privata e vista panoramica su Ipanema e Leblon. Palestra, piscina condominiale.",
    nightlyPrice: 2700,
    currency: "BRL",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 94,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Penthouse",
    latitude: -22.9839,
    longitude: -43.2096,
    address: "Ipanema",
    city: "Rio de Janeiro",
    countryCode: "BR",
    originalUrl: "https://www.airbnb.com/rooms/77889922",
    sourceListingId: "fb-br-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // South Africa
  {
    id: "fb-za-1",
    title: "Villa con piscina a Camps Bay – Città del Capo",
    description: "Spettacolare villa moderna a Camps Bay con piscina privata e viste panoramiche sull'Oceano Atlantico e le Twelve Apostles.",
    nightlyPrice: 7500,
    currency: "ZAR",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 67,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Villa",
    latitude: -33.9489,
    longitude: 18.3784,
    address: "Camps Bay",
    city: "Cape Town",
    countryCode: "ZA",
    originalUrl: "https://www.vrbo.com/6789012",
    sourceListingId: "fb-za-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Canada
  {
    id: "fb-ca-1",
    title: "Trendy Condo a Le Plateau – Montréal",
    description: "Accogliente condo nel vivace Plateau-Mont-Royal, il quartiere artistico di Montréal. Vicino a caffè, mercati e parchi.",
    nightlyPrice: 120,
    currency: "CAD",
    platform: "Airbnb",
    rating: 4.7,
    reviewCount: 263,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    propertyType: "Condo",
    latitude: 45.5233,
    longitude: -73.5795,
    address: "Plateau-Mont-Royal",
    city: "Montreal",
    countryCode: "CA",
    originalUrl: "https://www.airbnb.com/rooms/88990033",
    sourceListingId: "fb-ca-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Morocco
  {
    id: "fb-ma-1",
    title: "Riad autentico nella Medina – Marrakech",
    description: "Riad del XII secolo perfettamente restaurato nella medina di Marrakech. Patio con fontana, terrazza panoramica, hammam.",
    nightlyPrice: 165,
    currency: "EUR",
    platform: "Booking",
    rating: 4.9,
    reviewCount: 318,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    propertyType: "Riad",
    latitude: 31.6295,
    longitude: -7.9811,
    address: "Medina",
    city: "Marrakech",
    countryCode: "MA",
    originalUrl: "https://www.booking.com/hotel/ma/riad-medina-marrakech.html",
    sourceListingId: "fb-ma-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Switzerland
  {
    id: "fb-ch-1",
    title: "Chalet di montagna a Zermatt",
    description: "Autentico chalet svizzero a Zermatt con vista diretta sul Cervino. Sauna privata, ski-in/ski-out, fireplace.",
    nightlyPrice: 890,
    currency: "CHF",
    platform: "VRBO",
    rating: 4.9,
    reviewCount: 54,
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Chalet",
    latitude: 46.0207,
    longitude: 7.7491,
    address: "Zermatt",
    city: "Zermatt",
    countryCode: "CH",
    originalUrl: "https://www.vrbo.com/7890123",
    sourceListingId: "fb-ch-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Norway
  {
    id: "fb-no-1",
    title: "Idretts-Hytte sui fiordi – Bergen",
    description: "Tradizionale hytte norvegese con vista mozzafiato sul fiordo di Bergen. Barca inclusa, kayak disponibile, aurora boreale in inverno.",
    nightlyPrice: 2450,
    currency: "NOK",
    platform: "Airbnb",
    rating: 4.9,
    reviewCount: 88,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Cabin",
    latitude: 60.3913,
    longitude: 5.3221,
    address: "Osterøy",
    city: "Bergen",
    countryCode: "NO",
    originalUrl: "https://www.airbnb.com/rooms/99001133",
    sourceListingId: "fb-no-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Singapore
  {
    id: "fb-sg-1",
    title: "Modern Condo near Gardens by the Bay – Singapore",
    description: "Stylish condo in Marina Bay with stunning views of the Singapore skyline and Gardens by the Bay. Pool, gym, 24h concierge.",
    nightlyPrice: 220,
    currency: "SGD",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 167,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "Condo",
    latitude: 1.2793,
    longitude: 103.863,
    address: "Marina Bay",
    city: "Singapore",
    countryCode: "SG",
    originalUrl: "https://www.airbnb.com/rooms/10001001",
    sourceListingId: "fb-sg-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  // Argentina
  {
    id: "fb-ar-1",
    title: "Loft di design a Palermo – Buenos Aires",
    description: "Luminoso loft di design nel quartiere Palermo Soho, il cuore bohémien di Buenos Aires. Patio con jacuzzi.",
    nightlyPrice: 85,
    currency: "USD",
    platform: "Airbnb",
    rating: 4.8,
    reviewCount: 198,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    propertyType: "Loft",
    latitude: -34.5886,
    longitude: -58.4304,
    address: "Palermo Soho",
    city: "Buenos Aires",
    countryCode: "AR",
    originalUrl: "https://www.airbnb.com/rooms/20002002",
    sourceListingId: "fb-ar-1",
    provider: "fallback",
    lastSeenAt: "2026-05-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
];

function parseNumber(value: string | null, fieldName: string) {
  if (value === null) {
    return null;
  }

  const parsed = Number(value);

  if (!Number.isFinite(parsed)) {
    throw new Error(`Invalid ${fieldName}`);
  }

  return parsed;
}

export async function GET(request: NextRequest) {
  try {
    if (!process.env.DATABASE_URL) {
      return NextResponse.json({ data: FALLBACK_LISTINGS });
    }

    const searchParams = request.nextUrl.searchParams;

    const minLat = parseNumber(searchParams.get("minLat"), "minLat");
    const maxLat = parseNumber(searchParams.get("maxLat"), "maxLat");
    const minLng = parseNumber(searchParams.get("minLng"), "minLng");
    const maxLng = parseNumber(searchParams.get("maxLng"), "maxLng");

    if (minLat === null || maxLat === null || minLng === null || maxLng === null) {
      return NextResponse.json({ error: "Bounding box parameters are required" }, { status: 400 });
    }

    const platformValues = [
      ...searchParams.getAll("platform"),
      ...((searchParams.get("platform") || "").includes(",")
        ? String(searchParams.get("platform"))
            .split(",")
            .map((item) => item.trim())
            .filter(Boolean)
        : []),
    ];

    const listings = await getListingsByBbox({
      minLat,
      maxLat,
      minLng,
      maxLng,
      minNightlyPrice: parseNumber(searchParams.get("minNightlyPrice"), "minNightlyPrice") ?? undefined,
      maxNightlyPrice: parseNumber(searchParams.get("maxNightlyPrice"), "maxNightlyPrice") ?? undefined,
      minRating: parseNumber(searchParams.get("minRating"), "minRating") ?? undefined,
      maxGuests: parseNumber(searchParams.get("maxGuests"), "maxGuests") ?? undefined,
      countryCode: searchParams.get("countryCode") ?? undefined,
      platform: platformValues.length ? [...new Set(platformValues)] : undefined,
      queryText: searchParams.get("q") ?? undefined,
      limit: parseNumber(searchParams.get("limit"), "limit") ?? undefined,
      offset: parseNumber(searchParams.get("offset"), "offset") ?? undefined,
    });

    return NextResponse.json({ data: listings });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected error";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
